version: 0.2
phases:
  install:
    commands:
      # 1. Move into the client directory
      - cd client
      # 2. Install dependencies for the frontend
      - npm install
  build:
    commands:
      # 3. Run the build command (Vite and esbuild)
      - npm run build
      # 4. Move back to the root of the project
      - cd ..
artifacts:
  files:
    # 5. Package the entire repository for Elastic Beanstalk
    # This includes the server, the built client files, and all config
    - '**/*'
  discard-paths: yes
